name: Build and Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk upx-ucl

      - name: Install UPX (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install upx

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with Flet pack (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          flet pack main.py --name AdminPanel-Windows --icon "icon.png" --add-data "fonts;fonts" --add-data "icon.png;." -y --exclude-module numpy --exclude-module PIL --exclude-module tkinter --exclude-module pandas --exclude-module matplotlib --exclude-module IPython --exclude-module pytest --exclude-module unittest --exclude-module pydoc --exclude-module sqlite3 --exclude-module setuptools --exclude-module IPython --exclude-module notebook --exclude-module scipy

      - name: Build with Flet pack (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          flet pack main.py --name AdminPanel-Linux --add-data "fonts:fonts" --add-data "icon.png:." -y --exclude-module numpy --exclude-module PIL --exclude-module tkinter --exclude-module pandas --exclude-module matplotlib --exclude-module IPython --exclude-module pytest --exclude-module unittest --exclude-module pydoc --exclude-module sqlite3 --exclude-module setuptools --exclude-module IPython --exclude-module notebook --exclude-module scipy

      - name: Upload Release Asset (Windows)
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/AdminPanel-Windows.exe

      - name: Upload Release Asset (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/AdminPanel-Linux
